// Maps the exception messages raised by our RPCs (supabase/migrations/..._functions.sql) to HTTP
// status codes, so each Edge Function doesn't have to repeat this table.
const STATUS_BY_MESSAGE: Record<string, number> = {
  LOBBY_NOT_FOUND: 404,
  LOBBY_NOT_OPEN: 410,
  LOBBY_NOT_DRAFT: 409,
  LOBBY_FULL: 409,
  NOT_JOINED: 403,
  INVALID_OPTION: 400,
  INVALID_QUESTION: 400,
  INVALID_ACTION: 400,
  FORBIDDEN: 403,
  AT_LEAST_ONE_QUESTION_REQUIRED: 400,
  AT_LEAST_TWO_OPTIONS_REQUIRED: 400,
  RESPONSE_TEXT_REQUIRED: 400,
  RESPONSE_TEXT_TOO_LONG: 400,
  INAPPROPRIATE_CONTENT: 400,
  RATE_LIMITED: 429,
  AT_LEAST_ONE_OPTION_REQUIRED: 400,
  MAX_SELECTIONS_EXCEEDED: 400,
  AT_LEAST_TWO_RANKED_OPTIONS_REQUIRED: 400,
  DUPLICATE_OPTION: 400,
  INVALID_MAX_SELECTIONS: 400,
  INVALID_API_KEY: 401,
  MISSING_CODE: 400,
  KEY_NOT_FOUND: 404,
  AUTH_UNAVAILABLE: 503,
};

export function statusForRpcError(message: string): number {
  return STATUS_BY_MESSAGE[message] ?? 400;
}
